In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
f = open("babies.-1ibz3w3-2h9hx4o.txt")

header = 0
lines = []

for l in f:
    if header == 0:
        header = l.split(" ")
        lines.append([x.strip('\n') for x in header])
    else:
        ln = []
        for d in l.split(" "):
            if( d == '' or d == "\n"):
                continue
            ln.append(int(d.strip('\n')))
        lines.append(ln)
f.close()

nf = open("babies.csv", "w")

for vector in lines:
    strl = ""
    for elem in vector:
        strl = strl + str(elem) + ","
    strl = strl[:-1] + "\n"
    nf.write(strl)

nf.close()

In [3]:
data = pd.read_csv("babies.csv")

#note 2 outliers exist
data = data[data["age"] < 90]
#note 13 outliers exist
data = data[data["gestation"] < 500]

data.sort_values(['bwt'])

data_s = data[data["smoke"] == 1]
data_ns = data[data["smoke"] == 0]

In [55]:
data.plot(x="age", y="bwt", kind="scatter")
data.plot(y="bwt", x="gestation", kind="scatter")
data.plot(x="age", y="gestation", kind="scatter")
plt.show()

In [15]:
data_s.plot(y="bwt", x="gestation", kind="scatter", grid=True, xticks=range(120,400,40),yticks = range(40,200,20))
data_ns.plot(y="bwt", x="gestation", kind="scatter", grid=True, xticks=range(120,400,40),yticks = range(40,200,20))

plt.show()

In [18]:
data_s.describe()

,bwt,gestation,parity,age,height,weight,smoke
count,479.000000,479.000000,479.000000,479.000000,479.000000,479.000000,479.0
mean,114.081420,277.991649,0.252610,26.749478,64.966597,159.672234,1.0
std,18.179821,15.086915,0.434963,5.653883,6.045411,167.173847,0.0
min,58.000000,223.000000,0.000000,15.000000,53.000000,87.000000,1.0
25%,101.500000,271.000000,0.000000,22.000000,63.000000,112.000000,1.0
50%,115.000000,279.000000,0.000000,26.000000,64.000000,125.000000,1.0
75%,126.000000,286.000000,1.000000,30.000000,66.000000,140.000000,1.0
max,163.000000,330.000000,1.000000,43.000000,99.000000,999.000000,1.0

In [17]:
data_ns.describe()

,bwt,gestation,parity,age,height,weight,smoke
count,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.0
mean,123.154372,280.178962,0.260929,27.536885,64.390710,148.493169,0.0
std,17.353473,16.637585,0.439442,5.836346,4.391301,128.932548,0.0
min,55.000000,148.000000,0.000000,17.000000,56.000000,89.000000,0.0
25%,113.000000,273.000000,0.000000,23.000000,62.000000,115.000000,0.0
50%,123.500000,281.000000,0.000000,26.500000,64.000000,127.000000,0.0
75%,134.000000,289.000000,1.000000,31.000000,66.000000,140.000000,0.0
max,176.000000,353.000000,1.000000,45.000000,99.000000,999.000000,0.0

In [29]:
data = pd.read_csv("babies23.csv")

#note 2 outliers exist
data = data[data["age"] < 90]
#note 13 outliers exist
data = data[data["gestation"] < 500]

del data["outcome"]
del data["sex"]


data

,id,pluralty,date,gestation,wt,parity,race,age,ed,ht,...,drace,dage,ded,dht,dwt,marital,inc,smoke,time,number
0,15,5,1411,284,120,1,8,27,5,62,...,8,31,5,65,110,1,1,0,0,0
1,20,5,1499,282,113,2,0,33,5,64,...,0,38,5,70,148,1,4,0,0,0
2,58,5,1576,279,128,1,0,28,2,64,...,5,32,1,99,999,1,2,1,1,1
4,72,5,1425,282,108,1,0,23,5,67,...,0,24,5,99,999,1,1,1,1,5
5,100,5,1673,286,136,4,0,25,2,62,...,3,28,2,64,130,1,4,2,2,2
6,102,5,1449,244,138,4,7,33,2,62,...,7,37,4,99,999,1,98,0,0,0
7,129,5,1562,245,132,2,7,23,1,65,...,7,23,4,71,192,1,2,0,0,0
8,142,5,1408,289,120,3,0,25,4,62,...,3,26,1,70,180,0,2,0,0,0
9,148,5,1568,299,143,3,0,30,5,66,...,0,34,5,99,999,1,2,1,1,4
10,164,5,1554,351,140,2,0,27,5,68,...,5,28,4,99,999,1,98,3,4,2
11,171,5,1593,282,144,4,0,32,2,64,...,0,36,1,74,185,1,2,1,1,1
12,175,5,1491,279,141,3,0,23,1,63,...,5,28,2,99,999,1,2,1,1,1
13,183,5,1446,281,110,5,8,36,5,61,...,0,32,5,99,999,1,2,1,1,2
14,194,5,1524,273,114,3,7,30,2,63,...,7,42,0,99,999,1,1,0,0,0
15,195,5,1501,285,115,4,7,38,2,63,...,7,37,0,71,205,1,1,0,0,0
16,207,5,1481,255,92,3,4,25,7,65,...,7,28,1,99,999,1,1,1,1,5
17,217,5,1605,261,115,3,3,33,2,60,...,3,33,2,70,140,1,4,1,1,5
18,239,5,1431,261,144,2,0,33,2,68,...,5,35,4,99,999,1,7,0,0,0
19,240,5,1647,288,119,3,0,43,2,66,...,0,45,2,73,195,1,5,1,1,6
20,253,5,1553,270,105,3,9,22,2,56,...,10,38,1,99,999,1,3,0,0,0
21,274,5,1554,274,115,1,4,27,4,67,...,5,26,4,73,180,1,3,1,1,9
22,291,5,1624,287,137,1,0,25,4,66,...,0,25,5,70,150,1,2,2,2,5
23,294,5,1630,276,122,6,7,30,1,68,...,9,38,1,73,196,1,2,0,0,0
24,310,5,1367,294,131,2,7,23,2,65,...,7,23,4,99,999,1,2,2,2,1
25,337,5,1589,261,103,6,4,27,1,65,...,4,29,1,99,999,1,6,1,1,5
26,357,5,1533,280,146,1,6,26,0,58,...,6,29,2,68,200,1,2,2,2,1
27,365,5,1464,266,114,2,0,20,2,65,...,0,25,2,99,999,1,2,1,1,2
28,375,5,1708,292,125,3,3,32,2,65,...,0,29,5,67,135,1,1,0,0,0
29,376,5,1710,274,114,2,0,28,5,66,...,0,31,5,70,168,1,6,1,1,5
30,404,5,1358,270,122,2,0,26,2,61,...,0,26,2,99,999,1,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,8633,5,1700,242,127,1,7,17,1,61,...,7,19,2,72,999,1,0,1,1,2
1207,8639,5,1697,247,87,0,7,18,1,66,...,7,24,4,67,140,1,98,1,1,2
1208,8659,5,1697,281,141,6,7,29,2,54,...,7,37,2,69,195,1,2,1,1,1
1209,8664,5,1645,283,144,0,0,25,2,66,...,0,27,1,71,165,1,6,3,4,5
1210,8687,5,1675,273,116,5,0,33,4,66,...,5,34,5,71,185,1,6,1,1,5
1211,8703,5,1644,265,75,1,0,21,1,65,...,0,29,1,67,150,1,2,1,1,5
1212,8716,5,1700,286,138,0,0,28,2,68,...,0,26,4,74,245,1,8,2,2,5
1213,8723,5,1691,271,99,4,7,39,1,69,...,7,39,0,69,185,1,98,3,5,5
1214,8724,5,1644,293,118,1,5,21,2,63,...,5,24,2,68,170,1,4,0,0,0
1215,8725,5,1710,267,152,3,0,28,2,99,...,0,28,4,99,999,1,3,1,1,5
1216,8727,5,1620,266,97,4,7,24,1,62,...,7,26,2,64,130,1,0,0,0,0
1217,8801,5,1659,319,146,2,0,28,2,66,...,5,33,5,73,180,1,9,0,0,0
1218,8811,5,1625,285,81,2,7,19,1,63,...,7,25,2,67,160,1,98,1,1,3
1219,8848,5,1705,321,110,2,7,28,2,66,...,7,32,1,70,190,1,5,0,0,0
1220,8864,5,1693,284,135,0,0,19,2,60,...,0,24,2,73,150,1,2,0,0,0
1221,8917,5,1653,290,114,0,0,21,4,65,...,4,22,2,73,150,1,1,1,1,5
1222,8951,5,1682,288,124,0,5,21,4,64,...,3,22,5,70,140,1,98,1,1,2
1223,8955,5,1692,262,115,0,0,23,2,64,...,1,24,4,73,201,1,98,1,1,7
1224,8960,5,1713,281,143,4,7,28,1,65,...,7,44,9,99,999,1,1,1,1,1
1225,8966,5,1675,287,113,0,3,29,5,70,...,2,32,2,99,999,1,9,1,1,2
1226,8987,5,1681,244,109,0,0,21,3,63,...,0,22,2,66,140,1,3,1,1,5
1227,8995,5,1704,278,103,2,0,30,1,60,...,4,24,1,71,182,1,1,1,1,5
1228,9016,5,1660,276,118,1,6,34,4,64,...,0,37,5,99,170,1,3,0,0,0
1229,9044,5,1683,290,127,2,0,27,4,65,...,0,42,5,66,140,1,7,3,8,1
1230,9120,5,1681,270,132,3,7,27,2,65,...,7,35,1,69,200,1,3,3,3,1
1231,9153,5,1672,275,113,0,0,27,5,60,...,0,32,4,72,190,1,4,0,0,0
1232,9163,5,1712,265,128,1,0,24,5,67,...,0,24,5,73,170,1,3,0,0,0
1233,9213,5,1672,291,130,4,1,30,2,65,...,2,30,5,70,180,1,3,1,1,2
1234,9229,5,1680,281,125,0,0,21,4,65,...,0,27,5,71,165,1,1,0,0,0
1235,9263,5,1668,297,117,4,0,38,4,65,...,4,34,1,68,172,1,6,0,0,0

In [26]:
data.describe()

,id,pluralty,outcome,date,gestation,sex,wt,parity,race,age,...,drace,dage,ded,dht,dwt,marital,inc,smoke,time,number
count,1221.000000,1221.0,1221.0,1221.000000,1221.000000,1221.0,1221.000000,1221.000000,1221.000000,1221.000000,...,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000,1221.000000
mean,6012.923014,5.0,1.0,1536.570844,279.339066,1.0,119.624079,1.921376,3.210483,27.248976,...,3.666667,30.747748,3.189189,81.695332,506.076986,1.038493,13.267813,0.865684,1.750205,2.611794
std,2247.422804,0.0,0.0,107.019161,16.038315,0.0,18.259030,1.906084,4.199230,5.767512,...,6.874241,8.541428,1.702288,14.278858,406.860933,0.327923,28.579934,1.162943,8.873926,8.939780
min,15.000000,5.0,1.0,1350.000000,148.000000,1.0,55.000000,0.000000,0.000000,15.000000,...,0.000000,18.000000,0.000000,60.000000,110.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5414.000000,5.0,1.0,1444.000000,272.000000,1.0,108.000000,0.000000,0.000000,23.000000,...,0.000000,25.000000,2.000000,70.000000,165.000000,1.000000,2.000000,0.000000,0.000000,0.000000
50%,6730.000000,5.0,1.0,1541.000000,280.000000,1.0,120.000000,1.000000,3.000000,26.000000,...,3.000000,29.000000,4.000000,73.000000,190.000000,1.000000,4.000000,1.000000,1.000000,1.000000
75%,7587.000000,5.0,1.0,1628.000000,288.000000,1.0,131.000000,3.000000,7.000000,31.000000,...,7.000000,35.000000,5.000000,99.000000,999.000000,1.000000,7.000000,1.000000,1.000000,3.000000
max,9263.000000,5.0,1.0,1714.000000,353.000000,1.0,176.000000,11.000000,99.000000,45.000000,...,99.000000,99.000000,9.000000,99.000000,999.000000,5.000000,98.000000,9.000000,99.000000,98.000000